OrdererOrgs:
  - Name: Orderer
    Domain: vehicle-exchange-network.com
    Specs:
      - Hostname: orderer
PeerOrgs:
 - Name: manufacturer
   Domain: manufacturer.vehicle-exchange-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
 - Name: individual1
   Domain: individual1.vehicle-exchange-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
 - Name: individual2
   Domain: individual2.vehicle-exchange-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
 - Name: individual3
   Domain: individual3.vehicle-exchange-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
 