version: '2'

volumes:
  orderer.vehicle-exchange-network.com:
  peer0.carcompany.vehicle-exchange-network.com:
  peer1.carcompany.vehicle-exchange-network.com:
  peer0.ind1.vehicle-exchange-network.com:
  peer1.ind1.vehicle-exchange-network.com:
  peer0.ind2.vehicle-exchange-network.com:
  peer1.ind2.vehicle-exchange-network.com:
  peer0.ind3.vehicle-exchange-network.com:
  peer1.ind3.vehicle-exchange-network.com:

networks:
  vehicle-exchange:

services:

  ca.carcompany.vehicle-exchange-network.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.carcompany.vehicle-exchange-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.carcompany.vehicle-exchange-network.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CARCOMPNAY_CA_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.carcompany.vehicle-exchange-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CARCOMPANY_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/carcompany.vehicle-exchange-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.carcompany.vehicle-exchange-network.com
    networks:
      - vehicle-exchange

  ca.ind1.vehicle-exchange-network.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.ind1.vehicle-exchange-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ind1.vehicle-exchange-network.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/MHRD_CA_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.ind1.vehicle-exchange-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/IND1_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/ind1.vehicle-exchange-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.ind1.vehicle-exchange-network.com
    networks:
      - vehicle-exchange

  ca.ind2.vehicle-exchange-network.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.ind2.vehicle-exchange-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ind2.vehicle-exchange-network.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/IND2_CA_PRIVATE_KEY
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.ind2.vehicle-exchange-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/IND3_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/ind2.vehicle-exchange-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.ind2.vehicle-exchange-network.com
    networks:
      - vehicle-exchange

  ca.ind3.vehicle-exchange-network.com:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.ind3.vehicle-exchange-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      # - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ind3.vehicle-exchange-network.com-cert.pem
      # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/IND3_CA_PRIVATE_KEY
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.ind3.vehicle-exchange-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/IND3_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/ind1.vehicle-exchange-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.ind3.vehicle-exchange-network.com
    networks:
      - vehicle-exchange

  orderer.vehicle-exchange-network.com:
    extends:
      file:   docker-base/docker-compose-base.yaml
      service: orderer.vehicle-exchange-network.com
    container_name: orderer.vehicle-exchange-network.com
    networks:
      - vehicle-exchange

  peer0.carcompany.vehicle-exchange-network.com:
    container_name: peer0.carcompany.vehicle-exchange-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.carcompany.vehicle-exchange-network.com
    networks:
      - vehicle-exchange

  peer1.carcompany.vehicle-exchange-network.com:
    container_name: peer1.carcompany.vehicle-exchange-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.carcompany.vehicle-exchange-network.com
    networks:
      - vehicle-exchange

  peer0.ind1.vehicle-exchange-network.com:
    container_name: peer0.ind1.vehicle-exchange-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.ind1.vehicle-exchange-network.com
    networks:
      - vehicle-exchange

  peer1.ind1.vehicle-exchange-network.com:
    container_name: peer1.ind1.vehicle-exchange-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.ind1.vehicle-exchange-network.com
    networks:
      - vehicle-exchange

  peer0.ind2.vehicle-exchange-network.com:
    container_name: peer0.ind2.vehicle-exchange-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.ind2.vehicle-exchange-network.com
    networks:
      - vehicle-exchange

  peer1.ind2.vehicle-exchange-network.com:
    container_name: peer1.ind2.vehicle-exchange-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.ind2.vehicle-exchange-network.com
    networks:
      - vehicle-exchange

  peer0.ind3.vehicle-exchange-network.com:
    container_name: peer0.ind3.vehicle-exchange-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.ind3.vehicle-exchange-network.com
    networks:
      - vehicle-exchange

  peer1.ind3.vehicle-exchange-network.com:
    container_name: peer1.ind3.vehicle-exchange-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.ind3.vehicle-exchange-network.com
    networks:
      - vehicle-exchange

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.carcompany.vehicle-exchange-network.com:7051
      - CORE_PEER_LOCALMSPID=carcompanyMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/carcompany.vehicle-exchange-network.com/peers/peer0.carcompany.vehicle-exchange-network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/carcompany.vehicle-exchange-network.com/peers/peer0.carcompany.vehicle-exchange-network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/carcompany.vehicle-exchange-network.com/peers/peer0.carcompany.vehicle-exchange-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/carcompany.vehicle-exchange-network.com/users/Admin@carcompany.vehicle-exchange-network.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/
   #   - ./../chaincode-advanced/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode-advanced/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - ca.carcompany.vehicle-exchange-network.com
      - ca.ind1.vehicle-exchange-network.com
      - ca.ind2.vehicle-exchange-network.com
      - orderer.vehicle-exchange-network.com
      - peer0.carcompany.vehicle-exchange-network.com
      - peer1.carcompany.vehicle-exchange-network.com
      - peer0.ind1.vehicle-exchange-network.com
      - peer1.ind1.vehicle-exchange-network.com
      - peer0.ind2.vehicle-exchange-network.com
      - peer1.ind2.vehicle-exchange-network.com
      - peer0.ind3.vehicle-exchange-network.com
      - peer1.ind3.vehicle-exchange-network.com
    networks:
      - vehicle-exchange

  chaincode:
    container_name: chaincode
    image: hyperledger/fabric-ccenv:latest
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=chaincode
      - CORE_PEER_ADDRESS=peer0.carcompany.vehicle-exchange-network.com:7051
      - CORE_PEER_LOCALMSPID=carcompanyMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/crypto/peerOrganizations/carcompany.vehicle-exchange-network.com/users/Admin@carcompany.vehicle-exchange-network.com/msp
      - CORE_TLS_CLIENT_KEY_PATH=/opt/gopath/src/crypto/peerOrganizations/carcompany.vehicle-exchange-network.com/users/Admin@carcompany.vehicle-exchange-network.com/tls/client.key
      - CORE_TLS_CLIENT_CERT_PATH=/opt/gopath/src/crypto/peerOrganizations/carcompany.vehicle-exchange-network.com/users/Admin@carcompany.vehicle-exchange-network.com/tls/client.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/crypto/peerOrganizations/carcompany.vehicle-exchange-network.com/users/Admin@carcompany.vehicle-exchange-network.com/tls/ca.crt
    working_dir: /opt/gopath/src/chaincode
    command: /bin/bash -c 'sleep 6000000'
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode:/opt/gopath/src/chaincode
     # - ./../chaincode-advanced:/opt/gopath/src/chaincode-advanced
      - ./crypto-config:/opt/gopath/src/crypto
    networks:
      - vehicle-exchange

